### ISSUE TITLE
Memory/load

### ISSUE THREAD

**Issue by rospogrigio** [rospogrigio/localtuya#116]
Hi @postlund , more than an issue is a discussion I'd like to have. In the recent weeks, I have noticed HA having an increasing load on my Rpi3, the memory usage increases and I have set an auto-reboot each morning. Also, I have load peaks during which the system becomes unresponsive, and I usually need to reboot it during the day. Now, I've been wondering whether this is due to HA, and also whether localtuya might play a role. I am a C++ developer so I don't know much about python and how it behaves with memory allocation but I would like to have your opinion, and also would like to know if anybody else noticed what I'm reporting.
Also, I don't know if you have any suggestion for troubleshooting, I am seriously thinking to upgrade to Rpi4 since this is becoming more and more annoying every day.
Thank you

**Comment by postlund** [comment]
It's an interesting problem to assess. To me, it's seems a bit unlikely that it would be because of `localtuya`, but we can't rule it out. The memory footprint should not be much higher than before I think, but since we buffer incoming data and process it differently, there will be some penalty. Still, not something I would expect to be noticeable. I guess disabling `localtuya` for a day or so and monitoring the situation would be a starting point? Maybe other people see similarities issues (feel free to raise your hand here)?

**Comment by rospogrigio** [comment]
Just to speak, this is my typical situation:
![image](https://user-images.githubusercontent.com/49229287/97150775-e7ef6780-176e-11eb-8c96-ca24caa8f1ae.png)

**Comment by rospogrigio** [comment]
And yes, localtuya seems to be not involved in this. This is the chart after I removed localtuya and restarted HA (at 9.40),
Please note the peak at 10.57.... don't know where it comes from.

![image](https://user-images.githubusercontent.com/49229287/97162177-1e34e300-177f-11eb-8a48-7b3dbcd3c3fb.png)

**Comment by postlund** [comment]
I feel that we can close this now.
