### ISSUE TITLE
Using localtuya

### ISSUE THREAD

**Issue by evmax** [rospogrigio/localtuya#156]
Hi guys, thank you for all the staff you did.

Could you clearify some questions about using Smart Life app / Tuya Smart and IoT platform

I've completed all the instruction, added tuya switches to IoT platform, discovered its ids and keys, added to HA. Everything is perfect, works and shows states.

But, then I decided to delete device from Smart Life app, because I thought that mine are already connected localy/directly from HA and there is no need in IoT Platform. After it, there were no devices in IoT Platform device list and HA lost the devices

1. Is it expected behaviour?
2. How devices interacts with IoT platform when they are connected to HA localy? This way: _HA -> IoT Platrform -> TuyaSwitch_ or _HA -> TuyaSwitch_ directly ? 
3. If directly, what is the purpose of IoT Platform in localtuya?

Thanks you for answers

**Comment by postlund** [comment]
If you delete them from the app, the devices are likely unprovisioned and lose their local key. Other people report the same thing, so it is likely expected behavior.

With this component so the communicate with the device directly (TCP port 6668). The Tuya platform is only initially needed to provision the device in order to get it connected to the wifi. Once that is done, you can disable internet access for the device.

**Comment by WizBangCrash** [comment]
@postlund When you say "disconnect internet access". Is that achieved by simply removing them from the TuyaSmart app, or do you have to do something else to stop them reporting back to tuya cloud?

**Comment by postlund** [comment]
@WizBangCrash You will have to do that by blocking access in your router/gateway/firewall, move them to a separate VLAN, block DNS entries to the tuya cloud or something similar.

**Comment by postlund** [comment]
I believe we have covered the question, so I will close the issue. Feel free to open again if you have any further inquiries 👍
