### ISSUE TITLE
Safe to Use?

### ISSUE THREAD

**Issue by WolfsWelpe** [rospogrigio/localtuya#336]
Hello,

Is this custom integration safe to use due to new Information:
https://www.home-assistant.io/blog/2021/01/22/security-disclosure/

**Comment by rospogrigio** [comment]
I frankly cannot imagine a way this integration would make HA unsafe. It does not call cloud APIs, does not expose methods, it is even designed to work in a LAN, so you could just close external ports and it would work anyway. Maybe @postlund would like to add something since he wrote more than 85% of the code but I quite believe he will confirm.

**Comment by postlund** [comment]
Yes, it's safe. It does not perform any I/O or communication with other parts of HA that would make it prone to the mentioned issues.

**Comment by WolfsWelpe** [comment]
Thank you very much for the clarification :D
