### ISSUE TITLE
Scenes not working

### ISSUE THREAD

**Issue by BigWebstas** [rospogrigio/localtuya#498]
I have some string lights that have 9 scenes i can set them via the cli
but in hass it wont work
![image](https://user-images.githubusercontent.com/2896329/120706111-eeb52a00-c475-11eb-8aba-6c9755254055.png)
I updated the scene list in light.py but it doesnt seem to want to send the value to the light
![image](https://user-images.githubusercontent.com/2896329/120706085-e6f58580-c475-11eb-804c-5418d2cd8afa.png)
They show up in hass
![image](https://user-images.githubusercontent.com/2896329/120706140-f70d6500-c475-11eb-9139-042e8ba17255.png)

Any help would be appreciated

**Comment by BigWebstas** [comment]
Disregard, it was a config issue.
For anyone with a Atomi outdoor string lights
if you want scenes to work you need to set color mode to the scene dps
![image](https://user-images.githubusercontent.com/2896329/120707345-6f285a80-c477-11eb-91c7-251512f48d75.png)

**Comment by CamSoper** [comment]
@BigWebstas I haven't implemented local-tuya yet, I'm just investigating. 

Are you able to set the colors for "Pick 2" through local-tuya?

**Comment by norburban** [comment]
@BigWebstas & @CamSoper  - would you mind sharing your current working configurations / modifications to get the Atomi String Lights working properly?

**Comment by CamSoper** [comment]
@norburban I'm sorry, years on and I still haven't done local Tuya, I'm still running my string lights in the cloud.

**Comment by CamSoper** [comment]
@norburban Please share your configs! I think I may take the leap this weekend.

**Comment by norburban** [comment]
@CamSoper, I believe this is all of it.  I'm also in Missouri, so reach out if you have issues.

### Easiest instructions to get the local key & troubleshoot:
-  https://www.youtube.com/watch?v=wtzw_d4KMEQ
- Choose Western US region on the iot.tuya.com site since you're in the U.S.

### Updated the file light.py with this:
_(I saved local copies of the original & my mods for reference / future updates)_
For good measure, I rebooted HA after making this change.
I see there's an open issue asking to allow this type of config override instead of updating the source code.  For now, this is the way:

SCENE_LIST_RGBW_255 = {
    "White": "white",
    "Color": "colour",
    "Strobe": "scene1",
    "Fade": "scene2",
    "Pulse": "scene3",
    "Blink": "scene4",
    "Chase": "scene5",
    "Christmas": "scene6",
    "America": "scene7",
    "Pick 2": "scene8",
    "Multi": "scene9",
}

### Adding an entry (Cloud API account configuration)

- API server region: us
- check the box for 'Do not configure a Cloud API account'
- do not enter anything into Client ID, Secret, User ID


### Configured a 'light' entity as follows:
with protocol version: 3.3 selected

Brightness: 3
Color temp: 4
Brightness lower: 0
Brightness upper: 100
Color mode: 2
Color: 5
Minimum color in K: 1500
Maximum color in K: 8000
Scene: 2

I'm not sure the Min/Max color in K is absolutely correct.  If you find time to fine-tune, let me know.

**Comment by CamSoper** [comment]
Thank you much, @norburban!

**Comment by norburban** [comment]
Hey there @CamSoper  - did you have a chance to give it a try?

**Comment by CamSoper** [comment]
Thanks for the follow-up, @norburban! I haven't; I've been pretty swamped with family stuff these past few weeks. I really do appreciate it!
