### ISSUE TITLE
How to set value of numerical state for dp (use "states")?

### ISSUE THREAD

**Issue by Sergmasharov** [rospogrigio/localtuya#626]
Hello! I try to set temperature to my bht-002.
my server:
core-2021.9.7
supervisor-2021.10.8
Debian GNU/Linux 11 (bullseye)

I do like this
  action:
    - service: localtuya.set_dp
      data_template:
       device_id: *******
       dp: 2
       value: "{{states('input_number.bath_set_floor_temp' )}}"

If i do like shown below it works fine!
   action:
    - service: localtuya.set_dp
      data_template:
       device_id: *******
       dp: 2
       value: 29

How i can use "states" for localtuya values? I think i have a mistake in syntax.

**Comment by fimholz** [comment]
I have the same problem with a smart kettle and found out the following:

**When using the number directly:**
```
- service: localtuya.set_dp
  data: device_id: !secret tuya_kettle_device_id
  dp: 101
  value: "0" # quotes needed, otherwise the device crashes and reboots
```
`DEBUG (MainThread) [custom_components.localtuya.pytuya] [240...1bb] Send payload: b'{"devId":"***","uid":"***","t":"1640898943","dps":{"101":"0"}}'`

**When using a template**
```
- service: localtuya.set_dp
  data: device_id: !secret tuya_kettle_device_id
  dp: 101
  value: "{{ states('input_select.kettle_mode').split(':')[0] }}" # where input_select is "0": 45°C
```
`DEBUG (MainThread) [custom_components.localtuya.pytuya] [240...1bb] Send payload: b'{"devId":"***","uid":"***","t":"1640898943","dps":{"101":"\\"0\\""}}'
`

It seems that somewhere the quotes are being escaped but I cannot figure out if it is caused by Home Assistant template or in localtuya. Someone here who can help or give hints?

**Comment by fimholz** [comment]
@Sergmasharov sorry for using your issue for my problem which I think of now is not related to yours, but I think I can help you. Try to modify your template like that, note the `|int`
`value: "{{ states('input_number.bath_set_floor_temp')|int }}"`
Since [input_number](https://www.home-assistant.io/integrations/input_number/#input_number) is a floating point number, you should cast it to an integer.

**Update for my problem**
I modified the set_dp function in pytuya/__init__.py as follows (the isinstance check). This replaces the quotation marks if the passed value is a string and re-cast it to a string. This way it is also possible to pass integers to the exchange-function call as it was without the change.
```
    async def set_dp(self, value, dp_index):
        """
        Set value (may be any type: bool, int or string) of any dps index.

        Args:
            dp_index(int):   dps index to set
            value: new value for the dps index
        """
        if isinstance(value,str):
            value = str(value.replace('"', '').replace("'",""))
        return await self.exchange(SET, {str(dp_index): value})
```
I'm sure there exists a much better way to get rid of this, but for now it works for me.

**Comment by Sergmasharov** [comment]
Yeh! Thank you! You really help me! It works!
