### ISSUE TITLE
Add release notes for 3.3.0, 3.4.0, so that these are installable via HACS (Fix SPEED_HIGH issues on 2022.04)

### ISSUE THREAD

**Issue by CloCkWeRX** [rospogrigio/localtuya#785]
## The problem

Via HACS the latest release available is marked as 3.2.4.
I think this is due to tags existing, but not being marked as a release for 3.3.0, 3.4.0.

Fixes #780 
Fixes #784
Fixes #789 
Fixes #792

**Comment by CloCkWeRX** [comment]
@rospogrigio would it be possible to knock this one off, there's a fair few people being bitten by the older release of localtuya vs the newer homeassistant.

**Comment by rospogrigio** [comment]
> Via HACS the latest release available is marked as 3.2.4. I think this is due to tags existing, but not being marked as a release for 3.3.0, 3.4.0.

Mmmm... I don't understand what's going on. I actually created all the releases in the same way, I don't know why HACS is treating them differently. Moreover, I'm not sure which is the release being installed because I see both releases mentioned in the Information tab:
![image](https://user-images.githubusercontent.com/49229287/162703544-2b74bbfc-bba9-4cd4-8529-4e6510dc0dbd.png)

I also had problems after the update to 202204 and didn't have time to look into it so I just reverted to 202203, now I see that somebody has identified the problem in the fan platform... I'll try it again.

If you have any suggestions, they are more than welcome, thank you!

**Comment by yousaf465** [comment]
Still showing up as 3.2.4 
![image](https://user-images.githubusercontent.com/83491212/162706691-a6c921d0-b66f-4b59-81d8-3be177370cad.png)

**Comment by rospogrigio** [comment]
Have you tried "Update information" ?

**Comment by rospogrigio** [comment]
I published a new release, 3.5.0, it should work, please check it out ...

**Comment by joe-sydney** [comment]
By the way, does the version number in manifest.json do anything at all? It currently remains at 3.2.1.

**Comment by CloCkWeRX** [comment]
(Closing as it is now working)

**Comment by rospogrigio** [comment]
> By the way, does the version number in manifest.json do anything at all? It currently remains at 3.2.1.

I don't know, I just forget to update that value almost every time... anyway, HACS seems to use only the tag used when publishing a new release, so I guess it can just be ignored....
