### ISSUE TITLE
Color temperature range

### ISSUE THREAD

**Issue by SmartM-ui** [rospogrigio/localtuya#91]
Hello,
thanking you for all the work, just for information and to keep track of the things to develop, as you advised me to do, I report that the color temperature works, but the value is not reported correctly and does not correspond with the balance of the SmartLife app and therefore of the light bulb.

You should be able to set the right range through a minimum and maximum value of the kelvin degrees supported by the bulb, as you did for the brightness.

Here are some examples:

Center of the slider on LocalTuya (color temp 258) corresponds to 13% on Smartlife app (instead it should be 50%)

Other test:

SmartLife color temp: 0%
LocalTuya color_temp: 370

SmartLife color temp: 10%
LocalTuya color_temp: 284

SmartLife color temp: 50%
LocalTuya color_temp: -57

SmartLife color temp: 100%
LocalTuya color temp: -480

Thanks

If you need more information I will be happy to provide it

Good night

**Comment by bamzero** [comment]
I have this issue also. I am using [Brilliant CCT Downlight (Trilogy)](https://www.brilliantsmart.com.au/smart-products/lighting/smart-trilogy/) which I think use a different range for brightness and color temp than other Tuya lights.

They use a range of 10 - 1000 for brightness which can be set, however there is no way enter custom mired values.

I have it working by modifying light.py values of MAX_MIRED to 500 and using 1000 instead of 255 for color_temp functions

Line 27: Change 370 to 500
Line 91, 134 and 135: Change 255 to 1000

Also after making the changes and rebooting, I started getting errors with the component not detecting any lights, rebooted again and it detected a few. Another reboot and all the lights were detected again.

At first I thought it was the changes I made, however I've just seen this issue #118 posted and it was the same errors I saw in my logs so I guess it was just a coincidence.

**Comment by postlund** [comment]
Is this fixed on `master` now?

**Comment by postlund** [comment]
I believe this is fixed now, so I will close the issue. Re-open if problem still exists.

**Comment by SmartM-ui** [comment]
@postlund 

Hi Pierre,
for me, on my bulbs, the problem has been solved!
THANKS
