### ISSUE TITLE
Reconfiguring tuya device (that is blocked accessing over the internet) requires reboot of HA to apply new configuration.

### ISSUE THREAD

**Issue by remlei** [rospogrigio/localtuya#975]
## The problem

Reconfiguring any tuya device requires a full restart of Home Assistant or else that device will just hang as Unavailable. Also as a side effect, other tuya device that is paried with localtuya will also totally stop working, toggle the switch, nothing. change the color of the bulb, nothing. Restart HA after reconfiguring a tuya device fixes it.

## Environment

- Localtuya version: 4.0.1
- Last working localtuya version (if known and relevant):  N/A
- Home Assistant Core version: Home Assistant 2022.7.6
- [] Are you using the Home Assistant Tuya Cloud component ? kind off...  read below
- [] Are you using the Tuya App in parallel ? no

## Steps to reproduce

before doing everything all of these, I actually have these tuya device in a separate IoT SSID that is totally offgrid, the only moment that these devices see light over the internet is when I  paired the thing using the mobile app, grabbed their localkey and added it to localtuya, after that, I basically reconfigured pfsense to block all connection except DHCP server, even DHCP server is not providing a gateway and dns ip, just plain ip address and its subnet.

1. Go reconfigure a single tuya device
2. made some changes and apply
3. profit, that reconfigured tuya device will be flagged as unavailable, while everything else will not respond to any command

to quick fix is either temporary allow internet connection of my tuya devices while configuring it, or spin a quick reboot on Home Assistant via Settings >> System and click the restart button on the upper right corner of the webpage.

edit: the configuration made on that tuya device is applied, its just this bug kills everything if you made any setting changes of tuya devices, else leave them alone, localtuya works great with this tuya device that is totally blocked internet access.

**Comment by n00bcodr** [comment]
Definitely something I have been facing as well. I thought it was just me.
I am facing this with devices that are connected to the internet too.

**Comment by IeuanK** [comment]
LocalTuya 4.x is so horribly broken I am about to just spend more money on better plugs. 

I have two HomeWizard Energy plugs that just do exactly what they need to without question, they're practically plug & play in Home Assistant and then immediately show up in Energy as well.  
I also have a bunch of Tuya plugs (LEDVance), and it's been absolute hell since the beginning.  
Ended up getting one plug to barely work inside Home Assistant through YAML config, but LocalTuya 4.x has removed that option. On top of that, it blocks the ability to create two entities that access the same ID, so you can't have a binary sensor and a switch both accessing the endpoint that handles the state of the plug.

No clue what they were thinking, they completely destroyed the usability of this integration.

**Comment by remlei** [comment]
fixed on version 4.1.0. I can now reconfigure everything without having to enable internet access to that tuya device.
