### ISSUE TITLE
Unable to add devices

### ISSUE THREAD

**Issue by itrazar** [rospogrigio/localtuya#998]
Hi,

I had localtuya working for a while and stopped working after my network setup changed. I tried removing localtuya and installing it again but to no avail. The auto discovery i have seen at the very first installation but not after installing it again so i have to add devices manually. I'm sure the required fields i entered are correct.

Is there a way to COMPLETELY remove localtuya so i can start fresh?

![image](https://user-images.githubusercontent.com/8904787/186675552-e0b9bf40-f34b-4c91-8368-2f63a7643373.png)

Consulting the log i see the following message while trying to manually add a device. 

Logger: homeassistant.components.number
Source: components/number/__init__.py:231
Integration: Number (documentation, issues)
First occurred: 14:55:21 (4 occurrences)
Last logged: 14:55:32

custom_components.localtuya.number::LocaltuyaNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.sonoff.number::XNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.sonoff.number::XPulseWidth is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

**Comment by besiktas97** [comment]
Wondering if local_tuya will be still maintenanced. Didnt hear anything of the creator of this integration for a while.

Many people have this issue with other issues that it isnt working that good anymore.

**Comment by itrazar** [comment]
What a shame. Ah well, no more tuya integration in HA then. Thanks for the response.

**Comment by Merril-r** [comment]
@rospogrigio Are you still maintaining this ?

**Comment by fumantsu** [comment]
> @rospogrigio Are you still maintaining this ?

Did you check the commit history?

**Comment by Merril-r** [comment]
> > @rospogrigio Are you still maintaining this ?
> 
> @Merril-r Did you check the commit history?

Was there a comment from the repository owner? Cause I did no see anything? If there was can you point me to please?

**Comment by fumantsu** [comment]
Last commit was in mid of August from the owner and in general he is doing commits in master every months. You should looks better.... I guess

**Comment by BrettEBowman** [comment]
> Last commit was in mid of August from the owner and in general he is doing commits in master every months. You should looks better.... I guess

I think that the more important question is whether or not the owner is still doing **releases**. The last release according to the repository was on June 27th--over 2 months ago!

**Comment by fumantsu** [comment]
I guess releases will happen when they are ready, especially when I see that it is a sole guy maintain this project. Now if two months is too long, omg, I think some people are having weird expectations from this project.

**Comment by Merril-r** [comment]
> Last commit was in mid of August from the owner and in general he is doing commits in master every months. You should look better.... I guess

I think you just need to relax a little. I never accused the repository owner of not maintaining. I simply asked if they were still maintiain as there were a lot of issues logged since the latest release.

**Comment by fumantsu** [comment]
It is always good to do a homework first also known as search before people
starting the "it's abandoned", "are you alive" etc.
You didn't even understand when i said about the commit history.

Just fyi, also for me doesn't work and I came here to see and seek help and
only thing was complains about abandoned project. Then i gone to the commit
history and i said what the hell these people are taking about, the
maintainer is still doing something even now which is summer and I'm many
countries is vacation period.

Send from my hotdog

**Comment by itrazar** [comment]
Just wanted to give an update to people who might face a similar problem. As i mentioned, after my network setup changed (added in Mesh networking), Localtuya stopped working and i couldn't get it to work. 

I then spend some time getting the ip adressing the same as i had it before the change. Now it all works again and I'm a happy man. So, FWIW you might want to have a look at your network setup if applicable to your situation.

**Comment by rospogrigio** [comment]
Hi, please cool down everybody. I just came back from vacation so now I can answer some questions.
First of all, let me clarify some points. This repository comes from me finding the way to interact with certain Tuya devices, plus a huge work from postlund to bring the code to a higher level and make the calls super responsive.
Now, postlund seems to have quite disappeared as he's probably super busy, like I am depending on the periods.
The difficult part of handling a project like localtuya is that:
- it involves a lot of types of devices (switches, covers, climates, lights, fans....) and I own only some of these, so I can test any update on a limited amount of devices
- some of these require specific commands/values to be sent to the various DPs

This, I feel localtuya is somewhat at the state-of-the-art now, at least for the devices I own. I made a **HUGE** work in June introducing 4.0.0, only because I did not like how postlund had set up the handling of the devices (one integration per device, while I think the best approach is having a unique integration), plus I wanted to introduce the auto-detection of local keys and get rid of the YAML configuration.
So, I'd consider my contribution to the coding quite finished, unless further necessities appear in the future. But I'm quite open to import and release contributions from other developers, with the following rules since I feel quite responsible towards the users base, being localtuya the "official" integration in HACS:
Rule 0: any new release must not break MY environment 😉 
Rule 1: if I cannot test the new code personally because I don't own the devices involved, I want some feedbacks from other users owning the same or similar devices and confirming that the proposed PR does work properly. I'll limit myself to check that it does not break rule 0 😉 
Rule 2: the new code must be as general as possible, to make it possible to be used by all devices. In other words, developers must refrain from the temptation to write code that is specifically tailored for their devices because they need a certain value to be sent in a specific way. The developer should find a way to make this general/configurable, and this is the hard part. This is the main reason I've refused or put on hold several PRs, until I see this rule fulfilled. Others just stop at Rule 1, not finding enough people to test and provide feedbacks.

This explains the frequency of the releases regarding localtuya, which in summary are: little time for me to test the PRs, and difficulties from the developers to fulfill the rules above.
Going to your issue @itrazar, it looks like you've fallen into some issue with the number platform, which I haven't coded and don't use and also I don't know how it works, maybe @sibowler who coded it might provide some support. 
Regarding your question about uninstalling localtuya completely, it should be sufficient to delete the integration (I am assuming that you are on 4.0.1 and you are not using YAML configuration). If you still get errors after that, you might want to check if some spurious broken configuration is still present in `<config_dir>/.storage/core.config_entries`.
Hope the above clarifies, thank you for your support and for reading this long post.
Bye
rospogrigio

**Comment by rospogrigio** [comment]
Ooops @itrazar , I had skipped your last comment. If you have solved your problem, please close this Issue.
Bye!
